//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intuit.Ipp.GlobalTaxService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intuit.Ipp.GlobalTaxService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Batch Id is already used within this batch..
        /// </summary>
        internal static string BatchIdAlreadyUsed {
            get {
                return ResourceManager.GetString("BatchIdAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BatchItem having Id {0} not found for removal..
        /// </summary>
        internal static string BatchItemIdNotFound {
            get {
                return ResourceManager.GetString("BatchItemIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Items in Batch Request exceeded the permissible limit of 25 items..
        /// </summary>
        internal static string batchItemsExceededMessage {
            get {
                return ResourceManager.GetString("batchItemsExceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while communicating with the Ids Server..
        /// </summary>
        internal static string CommunicationErrorMessage {
            get {
                return ResourceManager.GetString("CommunicationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided entity cannot be converted to IntuitEntity object..
        /// </summary>
        internal static string EntityConversionFailedMessage {
            get {
                return ResourceManager.GetString("EntityConversionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id of the entity cannot be null or empty..
        /// </summary>
        internal static string EntityIdNotNullMessage {
            get {
                return ResourceManager.GetString("EntityIdNotNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity.
        /// </summary>
        internal static string EntityString {
            get {
                return ResourceManager.GetString("EntityString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception has been generated: {0}.
        /// </summary>
        internal static string ExceptionGeneratedMessage {
            get {
                return ResourceManager.GetString("ExceptionGeneratedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ids Logger cannot be null..
        /// </summary>
        internal static string IdsLoggerNotNullMessage {
            get {
                return ResourceManager.GetString("IdsLoggerNotNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string IdString {
            get {
                return ResourceManager.GetString("IdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pageNumber.
        /// </summary>
        internal static string PageNumberString {
            get {
                return ResourceManager.GetString("PageNumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pageSize.
        /// </summary>
        internal static string PageSizeString {
            get {
                return ResourceManager.GetString("PageSizeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be null..
        /// </summary>
        internal static string ParameterNotNullMessage {
            get {
                return ResourceManager.GetString("ParameterNotNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be zero or negative value..
        /// </summary>
        internal static string ParameterZeroNegativeValueMessage {
            get {
                return ResourceManager.GetString("ParameterZeroNegativeValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Request Validator cannot be null..
        /// </summary>
        internal static string RequestValidatorNotNullMessage {
            get {
                return ResourceManager.GetString("RequestValidatorNotNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Response Stream was null or empty..
        /// </summary>
        internal static string ResponseStreamNullOrEmptyMessage {
            get {
                return ResourceManager.GetString("ResponseStreamNullOrEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Context cannot be null..
        /// </summary>
        internal static string ServiceContextNotNullMessage {
            get {
                return ResourceManager.GetString("ServiceContextNotNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serviceContext.
        /// </summary>
        internal static string ServiceContextParameterName {
            get {
                return ResourceManager.GetString("ServiceContextParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status not deleted. .
        /// </summary>
        internal static string StatusNotDeleted {
            get {
                return ResourceManager.GetString("StatusNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status not voided..
        /// </summary>
        internal static string StatusNotVoided {
            get {
                return ResourceManager.GetString("StatusNotVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string parameter can not be null or empty..
        /// </summary>
        internal static string StringParameterNullOrEmpty {
            get {
                return ResourceManager.GetString("StringParameterNullOrEmpty", resourceCulture);
            }
        }
    }
}
