////*********************************************************
// <copyright file="GlobalSuppression.cs" company="Intuit">
//     Copyright (c) Intuit. All rights reserved.
// </copyright>
// <summary>This file contains Global Suppressions.</summary>
////***************************************************
using System.Diagnostics.CodeAnalysis;

[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ipp")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.IntuitServicesType.#IPS", MessageId = "IPS")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.IntuitServicesType.#QBD", MessageId = "QBD")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.IntuitServicesType.#QBO", MessageId = "QBO")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.HttpVerbType.#GET", MessageId = "GET")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.HttpVerbType.#POST", MessageId = "POST")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.HttpVerbType.#PUT", MessageId = "PUT")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.HttpVerbType.#DELETE", MessageId = "DELETE")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "Intuit.Ipp.Core.ASyncRestHandler", MessageId = "ASync")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#ID_DOMAIN_QUERY")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#ID_DOMAIN_QUERY", MessageId = "DOMAIN")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#ID_DOMAIN_QUERY", MessageId = "ID")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#ID_DOMAIN_QUERY", MessageId = "QUERY")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#API_GETIDSREALM")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#API_GETIDSREALM", MessageId = "GETIDSREALM")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#API_GETIDSREALM", MessageId = "API")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#IPS_BASEURL")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#IPS_BASEURL", MessageId = "IPS")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#IPS_BASEURL", MessageId = "BASEURL")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QBO_NAMESPACE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QBO_NAMESPACE", MessageId = "NAMESPACE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QBO_NAMESPACE", MessageId = "QBO")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#RESOURCE", MessageId = "RESOURCE")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_URLFORMENCODED")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_URLFORMENCODED", MessageId = "URLFORMENCODED")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_URLFORMENCODED", MessageId = "CONTENTTYPE")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#RESPONSEFILENAME_FORMAT")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#RESPONSEFILENAME_FORMAT", MessageId = "RESPONSEFILENAME")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#RESPONSEFILENAME_FORMAT", MessageId = "FORMAT")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#XOAUTHSERVICEPROVIDERID", MessageId = "XOAUTHSERVICEPROVIDERID")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#RESULTS_PERPAGE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#RESULTS_PERPAGE", MessageId = "PERPAGE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#RESULTS_PERPAGE", MessageId = "RESULTS")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QBD_BASEURL")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QBD_BASEURL", MessageId = "QBD")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QBD_BASEURL", MessageId = "BASEURL")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QBD_NAMESPACE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QBD_NAMESPACE", MessageId = "NAMESPACE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QBD_NAMESPACE", MessageId = "QBD")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#ISQBOXPATH", MessageId = "ISQBOXPATH")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#INTUITAUTH_HEADERFORMAT")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#INTUITAUTH_HEADERFORMAT", MessageId = "INTUITAUTH")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#INTUITAUTH_HEADERFORMAT", MessageId = "HEADERFORMAT")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#XOAUTHREALMIDPSEUDONYM", MessageId = "XOAUTHREALMIDPSEUDONYM")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#PAGE_NUM")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#PAGE_NUM", MessageId = "NUM")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#PAGE_NUM", MessageId = "PAGE")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#API_GETISREALMQBO")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#API_GETISREALMQBO", MessageId = "GETISREALMQBO")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#API_GETISREALMQBO", MessageId = "API")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#AUTHORIZATIONSTRING_FORHEADER")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#AUTHORIZATIONSTRING_FORHEADER", MessageId = "AUTHORIZATIONSTRING")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#AUTHORIZATIONSTRING_FORHEADER", MessageId = "FORHEADER")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_APPLICATIONXML")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_APPLICATIONXML", MessageId = "APPLICATIONXML")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_APPLICATIONXML", MessageId = "CONTENTTYPE")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#REQUESTFILENAME_FORMAT")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#REQUESTFILENAME_FORMAT", MessageId = "REQUESTFILENAME")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#REQUESTFILENAME_FORMAT", MessageId = "FORMAT")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#SLASH_CHAR")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#SLASH_CHAR", MessageId = "SLASH")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#SLASH_CHAR", MessageId = "CHAR")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#XOAUTHAUTHIDPSEUDONYM", MessageId = "XOAUTHAUTHIDPSEUDONYM")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#INTUIT_WORKPLACE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#INTUIT_WORKPLACE", MessageId = "WORKPLACE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#INTUIT_WORKPLACE", MessageId = "INTUIT")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_TEXTXML")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_TEXTXML", MessageId = "TEXTXML")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_TEXTXML", MessageId = "CONTENTTYPE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#REALMXPATH", MessageId = "REALMXPATH")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#VERSION", MessageId = "VERSION")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#APIACTIONHEADER", MessageId = "APIACTIONHEADER")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QB_COMMON_NAMESPACE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QB_COMMON_NAMESPACE", MessageId = "COMMON")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QB_COMMON_NAMESPACE", MessageId = "NAMESPACE")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#SYNC_TOKEN")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#SYNC_TOKEN", MessageId = "SYNC")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#SYNC_TOKEN", MessageId = "TOKEN")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#ERRORRESPONSEFILENAME_FORMAT")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#ERRORRESPONSEFILENAME_FORMAT", MessageId = "FORMAT")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#ERRORRESPONSEFILENAME_FORMAT", MessageId = "ERRORRESPONSEFILENAME")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QBO_BASEURL")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QBO_BASEURL", MessageId = "QBO")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#QBO_BASEURL", MessageId = "BASEURL")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#OAUTHACCESSTOKENURL", MessageId = "OAUTHACCESSTOKENURL")]

[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#appDbid")]
[module: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Intuit.Ipp.Core.Rest.LogRequestsToDisk.#LogPlatformRequests(System.String,System.Boolean)")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,System.String,Intuit.Ipp.Security.IRequestValidator)", MessageId = "Dbid")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,Intuit.Ipp.Security.IRequestValidator)", MessageId = "Dbid")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,System.String,System.String)", MessageId = "Dbid")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,System.String,Intuit.Ipp.Core.IntuitServicesType)", MessageId = "Dbid")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,System.String)", MessageId = "Dbid")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,System.String,System.String,Intuit.Ipp.Core.IntuitServicesType)", MessageId = "Dbid")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#GetQBOPartitionedURL(System.String)")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#GetIsRealmQbo()")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#GetIdsRealm()")]
[module: SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration", Scope = "member", Target = "Intuit.Ipp.Core.SyncRestHandler.#PrepareRequest(Intuit.Ipp.Core.RequestParameters,System.Object)", MessageId = "1#")]
[module: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", Scope = "member", Target = "Intuit.Ipp.Core.SyncRestHandler.#GetResponse(System.Net.HttpWebRequest)", MessageId = "errorResponse")]
[module: SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", Scope = "member", Target = "Intuit.Ipp.Core.RequestParameters.#.ctor(System.String,Intuit.Ipp.Core.HttpVerbType,System.String,System.String)", MessageId = "0#")]
[module: SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", Scope = "member", Target = "Intuit.Ipp.Core.RequestParameters.#.ctor(System.String,Intuit.Ipp.Core.HttpVerbType,System.String)", MessageId = "0#")]
[module: SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#BaseUrl")]
[module: SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Intuit.Ipp.Core.RequestParameters.#ResourceUri")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_APPLICATIONJSON")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_APPLICATIONJSON", MessageId = "APPLICATIONJSON")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_APPLICATIONJSON", MessageId = "CONTENTTYPE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#DOMAIN", MessageId = "DOMAIN")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#METADATA", MessageId = "METADATA")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#SPARSE", MessageId = "SPARSE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#STATUS", MessageId = "STATUS")]

[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "namespace", Target = "Intuit.Ipp.Core.Rest", MessageId = "Ipp")]
[module: SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", Scope = "member", Target = "Intuit.Ipp.Core.Rest.RequestParameters.#.ctor(System.String,Intuit.Ipp.Core.HttpVerbType,System.String)", MessageId = "0#")]
[module: SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", Scope = "member", Target = "Intuit.Ipp.Core.Rest.RequestParameters.#.ctor(System.String,Intuit.Ipp.Core.HttpVerbType,System.String,System.String)", MessageId = "0#")]
[module: SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Intuit.Ipp.Core.Rest.RequestParameters.#ResourceUri")]
[module: SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "Intuit.Ipp.Core.Rest.RestHandler.#PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters,System.Object)", Justification = "Header values need to be in lowercase.")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTENCODING", MessageId = "CONTENTENCODING", Justification = "This naming convention is used in all over the project.")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#ACCEPTENCODING", MessageId = "ACCEPTENCODING", Justification = "This naming convention is used in all over the project.")]
[module: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,System.String,Intuit.Ipp.Security.IRequestValidator)")]
[module: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#.ctor(System.String,System.String,Intuit.Ipp.Core.IntuitServicesType,Intuit.Ipp.Security.IRequestValidator)")]
[module: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,System.String,Intuit.Ipp.Core.IntuitServicesType,System.String)")]
[module: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,System.String)")]
[module: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,Intuit.Ipp.Core.IntuitServicesType,System.String)")]
[module: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,Intuit.Ipp.Security.IRequestValidator)")]
[module: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#.ctor(System.String,Intuit.Ipp.Core.IntuitServicesType,Intuit.Ipp.Security.IRequestValidator)")]
[module: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,System.String,System.String)")]
[module: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Intuit.Ipp.Core.Rest.IRestHandler.#PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters,System.Object,System.String)")]
[module: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Intuit.Ipp.Core.Rest.SyncRestHandler.#PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters,System.Object,System.String)")]
[module: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Intuit.Ipp.Core.Rest.AsyncRestHandler.#PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters,System.Object,System.String)")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#AppDbId", MessageId = "Db")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "namespace", Target = "Intuit.Ipp.Core.Compression", MessageId = "Ipp")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,System.String,Intuit.Ipp.Core.IntuitServicesType,System.String)", MessageId = "Dbid")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#IppConfiguration", MessageId = "Ipp")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.ServiceContext.#Create(System.String,System.String,Intuit.Ipp.Core.IntuitServicesType,System.String)", MessageId = "Dbid")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "namespace", Target = "Intuit.Ipp.Core.Configuration", MessageId = "Ipp")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.Configuration.RequestLog.#EnableRequestResponsLogging", MessageId = "Respons")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.Configuration.BaseUrl.#Ips", MessageId = "Ips")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.Configuration.BaseUrl.#Qbo", MessageId = "Qbo")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.Configuration.BaseUrl.#Qbd", MessageId = "Qbd")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Intuit.Ipp.Core.Configuration.IppConfiguration", MessageId = "Ipp")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.Rest.IRestHandler.#PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters,System.Object,System.String)", MessageId = "oauth")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.Rest.SyncRestHandler.#PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters,System.Object,System.String)", MessageId = "oauth")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.Rest.AsyncRestHandler.#PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters,System.Object,System.String)", MessageId = "oauth")]
[module: SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", Scope = "member", Target = "Intuit.Ipp.Core.Rest.IRestHandler.#PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters,System.Object,System.String)", MessageId = "2#")]
[module: SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", Scope = "member", Target = "Intuit.Ipp.Core.Rest.SyncRestHandler.#PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters,System.Object,System.String)", MessageId = "2#")]
[module: SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", Scope = "member", Target = "Intuit.Ipp.Core.Rest.AsyncRestHandler.#PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters,System.Object,System.String)", MessageId = "2#")]
[module: SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Intuit.Ipp.Core.Configuration.BaseUrl.#OAuthAccessTokenUrl")]
[module: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Intuit.Ipp.Core.Compression")]
[module: SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "Intuit.Ipp.Core.CallCompletedEventArgs`1")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Intuit.Ipp.Core.Rest.AsyncRestHandler.#HandleErrors(System.String)")]
[module: SuppressMessage("Microsoft.Design", "CA1059:MembersShouldNotExposeCertainConcreteTypes", Scope = "member", Target = "Intuit.Ipp.Core.CoreHelper.#ParseResponseIntoXml(System.String)", MessageId = "System.Xml.XmlNode")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "Intuit.Ipp.Core.DataServiceCallback`1+FindAllCallCompletedEventHandler")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "Intuit.Ipp.Core.DataServiceCallback`1+AsyncCallCompletedEventHandler")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "Intuit.Ipp.Core.DataServiceCallback`1+CallCompletedEventHandler")]
[module: SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "Intuit.Ipp.Core.Rest.RestHandler.#PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters,System.Object,System.String)")]
[module: SuppressMessage("Microsoft.Design", "CA1003:UseGenericEventHandlerInstances", Scope = "type", Target = "Intuit.Ipp.Core.DataServiceCallback`1+FindAllCallCompletedEventHandler")]
[module: SuppressMessage("Microsoft.Design", "CA1003:UseGenericEventHandlerInstances", Scope = "type", Target = "Intuit.Ipp.Core.DataServiceCallback`1+AsyncCallCompletedEventHandler")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Intuit.Ipp.Core.FindAllCallCompletedEventArgs.#Entities")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#REQUESTSOURCEHEADER", MessageId = "REQUESTSOURCEHEADER", Justification = "This nameing is appropriate.")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_TEXTPLAIN", MessageId = "CONTENTTYPE", Justification = "This nameing is appropriate.")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_TEXTPLAIN", MessageId = "TEXTPLAIN", Justification = "This nameing is appropriate.")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_TEXTPLAIN", Justification = "This nameing is appropriate.")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_APPLICATIONTEXT", MessageId = "CONTENTTYPE", Justification = "This nameing is appropriate.")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_APPLICATIONTEXT", MessageId = "APPLICATIONTEXT", Justification = "This nameing is appropriate.")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Intuit.Ipp.Core.CoreConstants.#CONTENTTYPE_APPLICATIONTEXT", Justification = "This nameing is appropriate.")]