//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitAnyWhereAddin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IntuitAnywhereText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IntuitAnywhereText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntuitAnyWhereAddin.IntuitAnywhereText", typeof(IntuitAnywhereText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your consumer key from your Manage App page here..
        /// </summary>
        internal static string Comment001 {
            get {
                return ResourceManager.GetString("Comment001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your consumer secret from your Manage App page here..
        /// </summary>
        internal static string Comment002 {
            get {
                return ResourceManager.GetString("Comment002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your application token from your Manage App page here..
        /// </summary>
        internal static string Comment003 {
            get {
                return ResourceManager.GetString("Comment003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key below is added by Intuit Anywhere Addin. .
        /// </summary>
        internal static string comment004 {
            get {
                return ResourceManager.GetString("comment004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPP entry below is added by Intuit Anywhere Addin.  This entry causes duplicate HTML tag with  xmlns:ipp=&apos;&apos; added in pages rendered. You may remove this entry and place  xmlns:ipp=&apos;&apos; in original HTML tag..
        /// </summary>
        internal static string comment005 {
            get {
                return ResourceManager.GetString("comment005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intuit Anywhere.
        /// </summary>
        internal static string mainmenu {
            get {
                return ResourceManager.GetString("mainmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Java Script Library.
        /// </summary>
        internal static string menu01 {
            get {
                return ResourceManager.GetString("menu01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Open ID.
        /// </summary>
        internal static string menu02 {
            get {
                return ResourceManager.GetString("menu02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Connect to QuickBooks.
        /// </summary>
        internal static string menu03 {
            get {
                return ResourceManager.GetString("menu03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Blue Dot Menu.
        /// </summary>
        internal static string menu04 {
            get {
                return ResourceManager.GetString("menu04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data Services SDK.
        /// </summary>
        internal static string menu05 {
            get {
                return ResourceManager.GetString("menu05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string menu06 {
            get {
                return ResourceManager.GetString("menu06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Direct Connect to Intuit.
        /// </summary>
        internal static string menu07 {
            get {
                return ResourceManager.GetString("menu07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Disconnect.
        /// </summary>
        internal static string menu08 {
            get {
                return ResourceManager.GetString("menu08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command is not supported when debugging is going on..
        /// </summary>
        internal static string msg001 {
            get {
                return ResourceManager.GetString("msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no document open for this operation..
        /// </summary>
        internal static string msg002 {
            get {
                return ResourceManager.GetString("msg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no project to perform this operation..
        /// </summary>
        internal static string msg003 {
            get {
                return ResourceManager.GetString("msg003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project type is not supported..
        /// </summary>
        internal static string msg004 {
            get {
                return ResourceManager.GetString("msg004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intuit Anywhere Addin.
        /// </summary>
        internal static string msgdialogtitle {
            get {
                return ResourceManager.GetString("msgdialogtitle", resourceCulture);
            }
        }
    }
}
