//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntuitAnyWhereAddin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IntuitAnywhereResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IntuitAnywhereResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntuitAnyWhereAddin.IntuitAnywhereResources", typeof(IntuitAnywhereResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bluedot {
            get {
                object obj = ResourceManager.GetObject("bluedot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your consumer key from your Manage App page here..
        /// </summary>
        internal static string Comment001 {
            get {
                return ResourceManager.GetString("Comment001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your consumer secret from your Manage App page here..
        /// </summary>
        internal static string Comment002 {
            get {
                return ResourceManager.GetString("Comment002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your application token from your Manage App page here..
        /// </summary>
        internal static string Comment003 {
            get {
                return ResourceManager.GetString("Comment003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key below is added by Intuit Anywhere Addin. .
        /// </summary>
        internal static string comment004 {
            get {
                return ResourceManager.GetString("comment004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPP entry below is added by Intuit Anywhere Addin.  This entry causes duplicate HTML tag with  xmlns:ipp=&apos;&apos; added in pages rendered. You may remove this entry and place  xmlns:ipp=&apos;&apos; in original HTML tag..
        /// </summary>
        internal static string comment005 {
            get {
                return ResourceManager.GetString("comment005", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap connect_to_qb_16 {
            get {
                object obj = ResourceManager.GetObject("connect_to_qb_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dataservices {
            get {
                object obj = ResourceManager.GetObject("Dataservices", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap directconnect {
            get {
                object obj = ResourceManager.GetObject("directconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disconnect_from_qb_16 {
            get {
                object obj = ResourceManager.GetObject("disconnect_from_qb_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap docs {
            get {
                object obj = ResourceManager.GetObject("docs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrontrunnerLogo {
            get {
                object obj = ResourceManager.GetObject("FrontrunnerLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help_icon {
            get {
                object obj = ResourceManager.GetObject("Help_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JSlibrary {
            get {
                object obj = ResourceManager.GetObject("JSlibrary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logout_1 {
            get {
                object obj = ResourceManager.GetObject("logout_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logout_2 {
            get {
                object obj = ResourceManager.GetObject("logout_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intuit Anywhere.
        /// </summary>
        internal static string mainmenu {
            get {
                return ResourceManager.GetString("mainmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Javascript Library.
        /// </summary>
        internal static string menu01 {
            get {
                return ResourceManager.GetString("menu01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPP Support.
        /// </summary>
        internal static string menu010 {
            get {
                return ResourceManager.GetString("menu010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Runner for IPP.
        /// </summary>
        internal static string menu011 {
            get {
                return ResourceManager.GetString("menu011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Logout.
        /// </summary>
        internal static string menu012 {
            get {
                return ResourceManager.GetString("menu012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add OpenID.
        /// </summary>
        internal static string menu02 {
            get {
                return ResourceManager.GetString("menu02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Connect to QuickBooks.
        /// </summary>
        internal static string menu03 {
            get {
                return ResourceManager.GetString("menu03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Blue Dot Menu.
        /// </summary>
        internal static string menu04 {
            get {
                return ResourceManager.GetString("menu04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Intuit Data Services SDK.
        /// </summary>
        internal static string menu05 {
            get {
                return ResourceManager.GetString("menu05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string menu06 {
            get {
                return ResourceManager.GetString("menu06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Direct Connect to Intuit.
        /// </summary>
        internal static string menu07 {
            get {
                return ResourceManager.GetString("menu07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Disconnect.
        /// </summary>
        internal static string menu08 {
            get {
                return ResourceManager.GetString("menu08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPP Documentation.
        /// </summary>
        internal static string menu09 {
            get {
                return ResourceManager.GetString("menu09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intuit Data Services SDK Documentation.
        /// </summary>
        internal static string menu10 {
            get {
                return ResourceManager.GetString("menu10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Intuit Data Services SDK V3.
        /// </summary>
        internal static string menu11 {
            get {
                return ResourceManager.GetString("menu11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command is not supported when debugging is going on..
        /// </summary>
        internal static string msg001 {
            get {
                return ResourceManager.GetString("msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no document open for this operation..
        /// </summary>
        internal static string msg002 {
            get {
                return ResourceManager.GetString("msg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no project to perform this operation..
        /// </summary>
        internal static string msg003 {
            get {
                return ResourceManager.GetString("msg003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project type is not supported..
        /// </summary>
        internal static string msg004 {
            get {
                return ResourceManager.GetString("msg004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add the Intuit Data Services SDK to your solution, you must have NuGet version 1.6 or later installed. Please visit http://NuGet.org/ to download and install the latest version..
        /// </summary>
        internal static string msg005 {
            get {
                return ResourceManager.GetString("msg005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a project to perform the selected operation..
        /// </summary>
        internal static string msg006 {
            get {
                return ResourceManager.GetString("msg006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intuit Anywhere Addin.
        /// </summary>
        internal static string msgdialogtitle {
            get {
                return ResourceManager.GetString("msgdialogtitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap openid {
            get {
                object obj = ResourceManager.GetObject("openid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Support {
            get {
                object obj = ResourceManager.GetObject("Support", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
