//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intuit.Ipp.PlatformService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "5.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intuit.Ipp.PlatformService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of administrators for all published applications not returned..
        /// </summary>
        internal static string AdminsForAllProductsNotRetuned {
            get {
                return ResourceManager.GetString("AdminsForAllProductsNotRetuned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AppToken cannot be empty..
        /// </summary>
        internal static string AppTokenCannotBeEmpty {
            get {
                return ResourceManager.GetString("AppTokenCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument {0} cannot be initialized with a negative value..
        /// </summary>
        internal static string ArgumentCannotBeNegative {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federated Identity for realm not returned..
        /// </summary>
        internal static string AssertFederatedIdentityNotRetuned {
            get {
                return ResourceManager.GetString("AssertFederatedIdentityNotRetuned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error with the certificate occurs..
        /// </summary>
        internal static string CertificateError {
            get {
                return ResourceManager.GetString("CertificateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate file could not be located on disk..
        /// </summary>
        internal static string CertificateNotFound {
            get {
                return ResourceManager.GetString("CertificateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while communicating with the Ids Server..
        /// </summary>
        internal static string CommunicationErrorMessage {
            get {
                return ResourceManager.GetString("CommunicationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdDomain of the entity cannot be null or empty..
        /// </summary>
        internal static string EntityIdDomainNotNullMessage {
            get {
                return ResourceManager.GetString("EntityIdDomainNotNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id of the entity cannot be null or empty..
        /// </summary>
        internal static string EntityIdNotNullMessage {
            get {
                return ResourceManager.GetString("EntityIdNotNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity.
        /// </summary>
        internal static string EntityString {
            get {
                return ResourceManager.GetString("EntityString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API response without Error code element..
        /// </summary>
        internal static string ErrorCodeMissing {
            get {
                return ResourceManager.GetString("ErrorCodeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code &quot;{0}&quot; not numeric!.
        /// </summary>
        internal static string ErrorCodeNonNemeric {
            get {
                return ResourceManager.GetString("ErrorCodeNonNemeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Error {1}, Detail: {2}).
        /// </summary>
        internal static string ErrorDetails0 {
            get {
                return ResourceManager.GetString("ErrorDetails0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Error {1}).
        /// </summary>
        internal static string ErrorDetails1 {
            get {
                return ResourceManager.GetString("ErrorDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}.
        /// </summary>
        internal static string ErrorWithNoText {
            get {
                return ResourceManager.GetString("ErrorWithNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception has been generated: {0}.
        /// </summary>
        internal static string ExceptionGeneratedMessage {
            get {
                return ResourceManager.GetString("ExceptionGeneratedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdDomain.
        /// </summary>
        internal static string IdDomainString {
            get {
                return ResourceManager.GetString("IdDomainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is not supported for the given entity..
        /// </summary>
        internal static string IdsMethodNotSupportedMessage {
            get {
                return ResourceManager.GetString("IdsMethodNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string IdString {
            get {
                return ResourceManager.GetString("IdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide account id..
        /// </summary>
        internal static string MustProvideAccountId {
            get {
                return ResourceManager.GetString("MustProvideAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide authIdPseudonym..
        /// </summary>
        internal static string MustProvideAuthIdPseudonym {
            get {
                return ResourceManager.GetString("MustProvideAuthIdPseudonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide content type..
        /// </summary>
        internal static string MustProvideContentType {
            get {
                return ResourceManager.GetString("MustProvideContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide database id..
        /// </summary>
        internal static string MustProvideDbId {
            get {
                return ResourceManager.GetString("MustProvideDbId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide email..
        /// </summary>
        internal static string MustProvideEmail {
            get {
                return ResourceManager.GetString("MustProvideEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide email or screen name..
        /// </summary>
        internal static string MustProvideEmailOrScreenName {
            get {
                return ResourceManager.GetString("MustProvideEmailOrScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide first name..
        /// </summary>
        internal static string MustProvideFirstName {
            get {
                return ResourceManager.GetString("MustProvideFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide keyFilePassword..
        /// </summary>
        internal static string MustProvideKeyFilePassword {
            get {
                return ResourceManager.GetString("MustProvideKeyFilePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide keyFilePath..
        /// </summary>
        internal static string MustProvideKeyFilePath {
            get {
                return ResourceManager.GetString("MustProvideKeyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide last name..
        /// </summary>
        internal static string MustProvideLastName {
            get {
                return ResourceManager.GetString("MustProvideLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide password..
        /// </summary>
        internal static string MustProvidePassword {
            get {
                return ResourceManager.GetString("MustProvidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide realm id..
        /// </summary>
        internal static string MustProvideRealmId {
            get {
                return ResourceManager.GetString("MustProvideRealmId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide realmIdPseudonym..
        /// </summary>
        internal static string MustProvideRealmIdPseudonym {
            get {
                return ResourceManager.GetString("MustProvideRealmIdPseudonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide role id..
        /// </summary>
        internal static string MustProvideRoleId {
            get {
                return ResourceManager.GetString("MustProvideRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide service provider id..
        /// </summary>
        internal static string MustProvideServiceProviderId {
            get {
                return ResourceManager.GetString("MustProvideServiceProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide userId..
        /// </summary>
        internal static string MustProvideUserId {
            get {
                return ResourceManager.GetString("MustProvideUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a valid Api Name..
        /// </summary>
        internal static string MustProvideValidApiName {
            get {
                return ResourceManager.GetString("MustProvideValidApiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a valid database id..
        /// </summary>
        internal static string MustProvideValidDbid {
            get {
                return ResourceManager.GetString("MustProvideValidDbid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No admin information returned..
        /// </summary>
        internal static string NoAdminInformationReturned {
            get {
                return ResourceManager.GetString("NoAdminInformationReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information returned from service..
        /// </summary>
        internal static string NoInformationReturnedFromService {
            get {
                return ResourceManager.GetString("NoInformationReturnedFromService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetIDSRealm did not return realm.
        /// </summary>
        internal static string NoRealmReturned {
            get {
                return ResourceManager.GetString("NoRealmReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role information returned..
        /// </summary>
        internal static string NoRoleInformationReturned {
            get {
                return ResourceManager.GetString("NoRoleInformationReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user information returned..
        /// </summary>
        internal static string NoUserInformationReturned {
            get {
                return ResourceManager.GetString("NoUserInformationReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user role information returned..
        /// </summary>
        internal static string NoUserRoleInformationReturned {
            get {
                return ResourceManager.GetString("NoUserRoleInformationReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pageNumber.
        /// </summary>
        internal static string PageNumberString {
            get {
                return ResourceManager.GetString("PageNumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pageSize.
        /// </summary>
        internal static string PageSizeString {
            get {
                return ResourceManager.GetString("PageSizeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of paid application subscriptions not returned..
        /// </summary>
        internal static string PaidSubscriptionNotRetuned {
            get {
                return ResourceManager.GetString("PaidSubscriptionNotRetuned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot have a negative value..
        /// </summary>
        internal static string ParameterNegativeValueMessage {
            get {
                return ResourceManager.GetString("ParameterNegativeValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be null..
        /// </summary>
        internal static string ParameterNotNullMessage {
            get {
                return ResourceManager.GetString("ParameterNotNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be zero or negative value..
        /// </summary>
        internal static string ParameterZeroNegativeValueMessage {
            get {
                return ResourceManager.GetString("ParameterZeroNegativeValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Response Stream was null or empty..
        /// </summary>
        internal static string ResponseStreamNullOrEmptyMessage {
            get {
                return ResourceManager.GetString("ResponseStreamNullOrEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action has exceeded its defined retry limit..
        /// </summary>
        internal static string RetryLimitExceeded {
            get {
                return ResourceManager.GetString("RetryLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service context cannot be null..
        /// </summary>
        internal static string ServiceContextCannotBeNull {
            get {
                return ResourceManager.GetString("ServiceContextCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of trail application subscriptions not returned..
        /// </summary>
        internal static string TrailSubscriptionNotRetuned {
            get {
                return ResourceManager.GetString("TrailSubscriptionNotRetuned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User text cannot be null..
        /// </summary>
        internal static string UserTextCannotBeNull {
            get {
                return ResourceManager.GetString("UserTextCannotBeNull", resourceCulture);
            }
        }
    }
}
