//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intuit.Ipp.Exception.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "5.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intuit.Ipp.Exception.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Items in Batch Request exceeded the permissible limit..
        /// </summary>
        internal static string BatchItemsExceededExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("BatchItemsExceededExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The communicating channel was terminated..
        /// </summary>
        internal static string ChannelTerminatedExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("ChannelTerminatedExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommunicationException was thrown..
        /// </summary>
        internal static string CommunicationExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("CommunicationExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ids service endpoint was not found..
        /// </summary>
        internal static string EndpointNotFoundExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("EndpointNotFoundExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault exception was raised..
        /// </summary>
        internal static string FaultExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("FaultExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdsError was thrown..
        /// </summary>
        internal static string IdsErrorDefaultMessage {
            get {
                return ResourceManager.GetString("IdsErrorDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ids exception was thrown..
        /// </summary>
        internal static string IdsExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("IdsExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter.
        /// </summary>
        internal static string InvalidParameterExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidParameterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm Id is invalid..
        /// </summary>
        internal static string InvalidRealmExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("InvalidRealmExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Request to the service is invalid..
        /// </summary>
        internal static string InvalidServiceRequestExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("InvalidServiceRequestExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Token is invalid..
        /// </summary>
        internal static string InvalidTokenExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("InvalidTokenExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ips exception thrown..
        /// </summary>
        internal static string IpsExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("IpsExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol exception was raised..
        /// </summary>
        internal static string ProtocolExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("ProtocolExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded retry attempts..
        /// </summary>
        internal static string RetryExceededExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("RetryExceededExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Policy Exception was raised..
        /// </summary>
        internal static string RetryExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("RetryExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdk Exception was thrown..
        /// </summary>
        internal static string SdkExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("SdkExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurityException was thrown..
        /// </summary>
        internal static string SecurityExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("SecurityExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization Exception was raised..
        /// </summary>
        internal static string SerializationExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("SerializationExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ids Server is too busy..
        /// </summary>
        internal static string ServerTooBusyExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("ServerTooBusyExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceException was thrown..
        /// </summary>
        internal static string ServiceExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("ServiceExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no response from the service..
        /// </summary>
        internal static string ServiceReturnedNoInformationExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("ServiceReturnedNoInformationExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttle Exception was thrown.
        /// </summary>
        internal static string ThrottleExceededExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("ThrottleExceededExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Exception was thrown..
        /// </summary>
        internal static string ValidationExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("ValidationExceptionDefaultMessage", resourceCulture);
            }
        }
    }
}
