//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intuit.Ipp.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intuit.Ipp.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appToken.
        /// </summary>
        internal static string AppTokenParameterName {
            get {
                return ResourceManager.GetString("AppTokenParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve BaseURI property. The given realm might not be part of QBO..
        /// </summary>
        internal static string BaseUriNullMessage {
            get {
                return ResourceManager.GetString("BaseUriNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while communicating with the Ids Server..
        /// </summary>
        internal static string CommunicationErrorMessage {
            get {
                return ResourceManager.GetString("CommunicationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CurrentCompany property of Quickbase Online User is null..
        /// </summary>
        internal static string CurrentCompanyNullMessage {
            get {
                return ResourceManager.GetString("CurrentCompanyNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string DefaultMinorVersionValue {
            get {
                return ResourceManager.GetString("DefaultMinorVersionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API response without Error code element..
        /// </summary>
        internal static string ErrorCodeMissing {
            get {
                return ResourceManager.GetString("ErrorCodeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code &quot;{0}&quot; not numeric!.
        /// </summary>
        internal static string ErrorCodeNonNemeric {
            get {
                return ResourceManager.GetString("ErrorCodeNonNemeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Error {1}, Detail: {2}).
        /// </summary>
        internal static string ErrorDetails0 {
            get {
                return ResourceManager.GetString("ErrorDetails0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Error {1}).
        /// </summary>
        internal static string ErrorDetails1 {
            get {
                return ResourceManager.GetString("ErrorDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}.
        /// </summary>
        internal static string ErrorWithNoText {
            get {
                return ResourceManager.GetString("ErrorWithNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception has been generated: {0}..
        /// </summary>
        internal static string ExceptionGeneratedMessage {
            get {
                return ResourceManager.GetString("ExceptionGeneratedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response did not contain the service type..
        /// </summary>
        internal static string NoServiceTypeResponseMessage {
            get {
                return ResourceManager.GetString("NoServiceTypeResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Cannot be null or empty..
        /// </summary>
        internal static string ParameterNotNullEmptyMessage {
            get {
                return ResourceManager.GetString("ParameterNotNullEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be null..
        /// </summary>
        internal static string ParameterNotNullMessage {
            get {
                return ResourceManager.GetString("ParameterNotNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The realm id for the appToken could not be found..
        /// </summary>
        internal static string RealmIdNotFoundMessage {
            get {
                return ResourceManager.GetString("RealmIdNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to realmId.
        /// </summary>
        internal static string RealmIdParameterName {
            get {
                return ResourceManager.GetString("RealmIdParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requestValidator.
        /// </summary>
        internal static string RequestValidatorParameterName {
            get {
                return ResourceManager.GetString("RequestValidatorParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Response Stream was null or empty..
        /// </summary>
        internal static string ResponseStreamNullOrEmptyMessage {
            get {
                return ResourceManager.GetString("ResponseStreamNullOrEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the response stream..
        /// </summary>
        internal static string ResponseStreamReadFailedMessage {
            get {
                return ResourceManager.GetString("ResponseStreamReadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deserialization to Quickbooks Online User failed..
        /// </summary>
        internal static string SerializationExceptionMessage {
            get {
                return ResourceManager.GetString("SerializationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid directory path..
        /// </summary>
        internal static string ValidDirectoryPathMessage {
            get {
                return ResourceManager.GetString("ValidDirectoryPathMessage", resourceCulture);
            }
        }
    }
}
